spring:
  application:
    name: eureka-server
  profiles:
    active: peer3-1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      
---
spring:
  profiles: peer3-1
server:
  port: 8761
      
---
spring:
  profiles: peer3-2
server:
  port: 8762
        
---
spring:
  profiles: peer3-3
server:
  port: 8763 
  
  
    
---
server:
  port: 8761
spring:
  profiles: peer2-1
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/
      
---
server:
  port: 8762
spring:
  profiles: peer2-2
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/