spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: provider-server
        uri: lb://provider-service
        predicates:
          - Path=/provider/**
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
        
    
---
server:
  port: 1001
spring:
  profiles: peer2-1
  
---
server:
  port: 1002
spring:
  profiles: peer2-2