spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: provider-server
        uri: lb://provider-service
        predicates:
          - Path=/provider/**
        filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redus-rate-limiter.burstCapacity: 5
      - id: jwt-service 
        uri: lb://jwt-service
        predicates:
          - Path=/jwt/** 
        filters:
          - StripPrefix=1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
        
    
---
server:
  port: 1001
spring:
  profiles: peer2-1
  
---
server:
  port: 1002
spring:
  profiles: peer2-2