spring:
  profiles:
    include: routers, jwt
  application:
    name: szbsc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
        
    
---
server:
  port: 1001
spring:
  profiles: peer2-1
  
---
server:
  port: 1002
spring:
  profiles: peer2-2