spring:
  application:
    name: szbsc-provider
  profiles: 
    active: peer2-1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  
---
server:
  port: 2001
spring:
  profiles: peer2-1

---
server:
  port: 2002
spring:
  profiles: peer2-2