spring:
  application:
    name: szbsc-consume
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
    #max-connections: 1000
    #max-connections-per-route: 100
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 1024
    response:
      enabled: true
      
logging:
  level:
    com.szbsc: debug
    
---
server:
  port: 3001
spring:
  profiles: peer2-1
  
eureka:
  instance:
    ip-address: 192.168.8.127
    instance-id: 192.168.8.127:3001
    prefer-ip-address: true
    
    
---
server:
  port: 3002
spring:
  profiles: peer2-2
  
eureka:
  instance:
    ip-address: 192.168.8.127
    instance-id: 192.168.8.127:3002
    prefer-ip-address: true
        
