server:
  port: 9001
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  
  
spring:
  datasource:
    master:
     jdbc-url: jdbc:mysql://192.168.8.127:3316/dosth?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull    #创建的数据库
     username: root
     password: 123
     driverClassName: com.mysql.cj.jdbc.Driver
    slave:
     jdbc-url: jdbc:mysql://192.168.8.127:3326/dosth?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull    #创建的数据库
     username: root
     password: 123
     driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy